var _yt_www={};(function(m){var window=this;var qa,ra;m.aa=function(a){return function(){return m.ca[a].apply(this,arguments)}};m.da=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.da(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.n=function(a,b){for(var c=a.split("."),d=b||m.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.Pb?a.Pb:a.Pb=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.ma=function(a){return"number"==typeof a};m.na=function(a){return"function"==m.ha(a)};m.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.pa=function(a){return a[qa]||(a[qa]=++ra)};
var sa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ta;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.D=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var ua=function(a){ua[" "](a);return a};m.va=function(a,b){try{return ua(a[b]),!0}catch(c){}return!1};
m.wa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.wa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.xa=function(a){return(0,window.encodeURIComponent)(String(a))};
m.ya=function(a){if(!za.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Aa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ba,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ca,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Da,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ea,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Fa,"&#0;"));return a};m.Ga=function(a,b){return-1!=a.indexOf(b)};m.Ha=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
m.Ja=function(a,b){for(var c=0,d=(0,m.Ka)(String(a)).split("."),e=(0,m.Ka)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",p=e[h]||"",v=RegExp("(\\d*)(\\D*)","g"),z=RegExp("(\\d*)(\\D*)","g");do{var N=v.exec(k)||["","",""],ba=z.exec(p)||["","",""];if(0==N[0].length&&0==ba[0].length)break;c=La(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==ba[1].length?0:(0,window.parseInt)(ba[1],10))||La(0==N[2].length,0==ba[2].length)||La(N[2],ba[2])}while(0==c)}return c};
var La=function(a,b){return a<b?-1:a>b?1:0};var Ma=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};m.Na=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Oa=function(a){var b=m.ka(void 0)?m.Ha(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Pa=function(a,b,c){b=m.Qa(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Qa=function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};m.Ra=function(a,b){return 0<=(0,m.Sa)(a,b)};m.Ta=function(a,b){var c=(0,m.Sa)(a,b),d;(d=0<=c)&&m.Ua(a,c);return d};m.Ua=function(a,b){m.Va.splice.call(a,b,1)};m.Wa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.gb=this.gb;this.Ya=this.Ya};m.Xa=function(a,b){m.Ya(a,m.r(m.Za,b))};
m.Ya=function(a,b){a.gb?b.call(void 0):(a.Ya||(a.Ya=[]),a.Ya.push(m.da(void 0)?(0,m.q)(b,void 0):b))};m.Za=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.$a=function(){m.u.call(this);this.j=[];this.xc={}};m.ab=function(a){bb(m.cb,arguments)};m.w=function(a,b){return a in m.cb?m.cb[a]:b};m.x=function(a,b){m.na(a)&&(a=m.db(a));return window.setTimeout(a,b)};m.eb=function(a,b){m.na(a)&&(a=m.db(a));return window.setInterval(a,b)};m.fb=function(a){window.clearTimeout(a)};m.gb=function(a){window.clearInterval(a)};
m.db=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.hb(b),b;}}:a};m.hb=function(a,b){var c=m.n("yt.www.errors.log");c?c(a,b):(c=m.w("ERRORS")||[],c.push([a,b]),m.ab("ERRORS",c))};m.ib=function(a){return a in m.jb};m.kb=function(a,b,c){var d=b||{};if(a=a in m.jb?m.jb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var bb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
m.y=function(a,b,c){var d=lb();if(d){var e=d.subscribe(a,function(){if(!mb||mb!=e){var d=arguments,h=function(){nb[e]&&b.apply(c||window,d)};try{ob[a]?h():m.x(h,0)}catch(k){m.hb(k)}}},c);nb[e]=!0;pb[a]||(pb[a]=[]);pb[a].push(e);return e}return 0};m.qb=function(a){var b=lb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a);delete nb[a]}))};m.B=function(a,b){var c=lb();return c?c.publish.apply(c,arguments):!1};
m.rb=function(a,b){ob[a]=!0;var c=lb(),c=c?c.publish.apply(c,arguments):!1;ob[a]=!1;return c};var lb=function(){return m.n("yt.pubsub.instance_")};m.sb=function(){return!!m.n("yt.scheduler.instance")};m.tb=function(a,b){void 0===b&&(b=window.NaN);var c=m.n("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.x(a,b||0)};m.ub=function(a,b){return m.tb(a,b)};m.vb=function(a){var b=m.n("yt.scheduler.instance.cancelJob");b?b(a):m.fb(a)};
m.wb=function(a){for(var b=0,c=a.length;b<c;b++)m.vb(a[b])};m.xb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.B=d?m.db(d):null;this.A=e?m.db(e):null;this.n=[];this.j=this.k=0};m.yb=function(a){m.vb(a.k);a.k=m.ub((0,m.q)(a.init,a))};m.zb=function(a){a.name in Ab&&Bb(a.name);Ab[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in Ab))throw Error("Module "+b+" required by "+a.name);Ab[b].reqs.push(a.name)});a.enable()};
var Bb=function(a){if(a in Ab){var b=Ab[a];(0,m.A)(b.reqs,function(a){Bb(a)});try{b.disable()}catch(c){}delete Ab[a]}};m.Cb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.Db=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.Fb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.Gb=function(a,b){b in a&&delete a[b]};m.Hb=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};m.Ib=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
m.Jb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Kb.length;f++)c=Kb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Lb=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return Lb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};m.Mb=function(){this.j="";this.k=Nb};m.Ob=function(a){return a instanceof m.Mb&&a.constructor===m.Mb&&a.k===Nb?a.j:"type_error:Const"};
m.Pb=function(){this.j="";this.k=Qb};m.Rb=function(a){return a instanceof m.Pb&&a.constructor===m.Pb&&a.k===Qb?a.j:"type_error:SafeStyle"};var Sb=function(a){var b=new m.Pb;b.j=a;return b};m.Tb=function(){this.j="";this.k=Ub};m.Vb=function(a){return a instanceof m.Tb&&a.constructor===m.Tb&&a.k===Ub?a.j:"type_error:SafeUrl"};m.Wb=function(a){if(a instanceof m.Tb)return a;a=a.Se?a.Ie():String(a);a=Xb.test(a)?Yb(a):"about:invalid#zClosurez";var b=new m.Tb;b.j=a;return b};
var Yb=function(a){try{var b=(0,window.encodeURI)(a)}catch(c){return"about:invalid#zClosurez"}return b.replace(Zb,function(a){return $b[a]})};var ac=function(){this.j=bc};m.cc=function(){this.j="";this.l=dc;this.k=null};m.ec=function(a){return a instanceof m.cc&&a.constructor===m.cc&&a.l===dc?a.j:"type_error:SafeHtml"};
var fc=function(a){function b(a){if(m.ia(a))(0,m.A)(a,b);else{var f;a instanceof m.cc?f=a:(f=null,a.rk&&(f=a.Dg()),a=m.ya(a.Se?a.Ie():String(a)),f=m.gc(a,f));d+=m.ec(f);f=f.Dg();0==c?c=f:0!=f&&c!=f&&(c=null)}}var c=0,d="";(0,m.A)(arguments,b);return m.gc(d,c)};m.gc=function(a,b){var c=new m.cc;c.j=a;c.k=b;return c};
m.hc=function(a,b){var c=null,d="<"+a;if(b)for(var e in b){if(!ic.test(e))throw Error('Invalid attribute name "'+e+'".');var f=b[e];if(null!=f){var h,k=a;h=e;if(f instanceof m.Mb)f=m.Ob(f);else if("style"==h.toLowerCase()){if(!m.oa(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof m.Pb)){var k="",p=void 0;for(p in f){if(!/^[-_a-zA-Z0-9]+$/.test(p))throw Error("Name allows only [-_a-zA-Z0-9], got: "+p);var v=f[p];
if(null!=v){if(v instanceof m.Mb)v=m.Ob(v);else if(jc.test(v)){for(var z=!0,N=!0,ba=0;ba<v.length;ba++){var la=v.charAt(ba);"'"==la&&N?z=!z:'"'==la&&z&&(N=!N)}z&&N||(v="zClosurez")}else v="zClosurez";k+=p+":"+v+";"}}f=k?Sb(k):kc}f=m.Rb(f)}else{if(/^on/i.test(h))throw Error('Attribute "'+h+'" requires goog.string.Const value, "'+f+'" given.');if(h.toLowerCase()in lc)if(f instanceof ac)f=f instanceof ac&&f.constructor===ac&&f.j===bc?"":"type_error:TrustedResourceUrl";else if(f instanceof m.Tb)f=m.Vb(f);
else throw Error('Attribute "'+h+'" on tag "'+k+'" requires goog.html.SafeUrl or goog.string.Const value, "'+f+'" given.');}f.Se&&(f=f.Ie());h=h+'="'+m.ya(String(f))+'"';d=d+(" "+h)}}e=void 0;m.da(e)?m.ia(e)||(e=[e]):e=[];!0===mc[a.toLowerCase()]?d+=">":(c=fc(e),d+=">"+m.ec(c)+"</"+a+">",c=c.Dg());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return m.gc(d,c)};m.nc=function(a,b){a.innerHTML=m.ec(b)};m.C=function(a,b){return a?a.dataset?a.dataset[m.oc(b)]:a.getAttribute("data-"+b):null};
m.pc=function(a,b){return a?a.dataset?m.oc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.oc=function(a){return qc[a]||(qc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.rc=function(a,b){var c=m.sc(a);window.spf.script.load(a,c,b)};
m.sc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(tc,""),b=b.replace(uc,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};m.vc=function(a,b,c){return Math.min(Math.max(a,b),c)};m.wc=function(a,b){this.x=m.da(a)?a:0;this.y=m.da(b)?b:0};m.xc=function(a){return m.Ga(m.yc,a)};var zc=function(){return m.xc("Opera")||m.xc("OPR")};var Ac=function(){return m.xc("Edge")||m.xc("Trident")||m.xc("MSIE")};
var Bc=function(){return(m.xc("Chrome")||m.xc("CriOS"))&&!zc()&&!Ac()};var Cc=function(){return m.xc("Edge")};m.Dc=function(){return m.xc("iPhone")&&!m.xc("iPod")&&!m.xc("iPad")};var Ec=function(){var a=m.yc;if(m.Fc)return/rv\:([^\);]+)(\)|;)/.exec(a);if(m.D&&Cc())return/Edge\/([\d\.]+)/.exec(a);if(m.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(m.Gc)return/WebKit\/(\S+)/.exec(a)};var Hc=function(){var a=m.ea.document;return a?a.documentMode:void 0};
m.Ic=function(a){return Jc[a]||(Jc[a]=0<=m.Ja(Kc,a))};m.Lc=function(a){return m.D&&(Cc()||m.Mc>=a)};m.E=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Nc=function(a){return m.ka(a)?window.document.getElementById(a):a};m.F=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Oc("*",a,b)[0];return d||null};
m.Oc=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Ra(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.Pc=function(a,b){m.Cb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Qc?a.setAttribute(Qc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Rc=function(a){var b=m.Sc(a);a=a.parentWindow||a.defaultView;return m.D&&m.Ic("10")&&a.pageYOffset!=b.scrollTop?new m.wc(b.scrollLeft,b.scrollTop):new m.wc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
m.Sc=function(a){return!m.Gc&&m.Tc(a)?a.documentElement:a.body||a.documentElement};m.Uc=function(a,b,c){return m.Vc(window.document,arguments)};m.Vc=function(a,b){var c=b[0],d=b[1];if(!Wc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.ya(d.name),'"');if(d.type){c.push(' type="',m.ya(d.type),'"');var e={};m.Jb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Pc(c,d));2<b.length&&m.Xc(a,c,b,2);return c};
m.Xc=function(a,b,c,d){function e(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ja(f)||m.oa(f)&&0<f.nodeType?e(f):(0,m.A)(Yc(f)?m.Wa(f):f,e)}};m.Tc=function(a){return"CSS1Compat"==a.compatMode};m.Zc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};m.$c=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};m.ad=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
var bd=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};var cd=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
m.dd=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};m.ed=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var Yc=function(a){if(a&&"number"==typeof a.length){if(m.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.na(a))return"function"==typeof a.item}return!1};
m.fd=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};m.gd=function(a){return function(){return a}};m.hd=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.id=function(){};
m.jd=function(a){if(a instanceof m.id)return a;if("function"==typeof a.Fb)return a.Fb(!1);if(m.ja(a)){var b=0,c=new m.id;c.next=function(){for(;;){if(b>=a.length)throw m.kd;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};m.ld=function(a,b,c){if(m.ja(a))try{(0,m.A)(a,b,c)}catch(d){if(d!==m.kd)throw d;}else{a=m.jd(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.kd)throw e;}}};
m.md=function(a){if(m.ja(a))return m.Wa(a);a=m.jd(a);var b=[];m.ld(a,function(a){b.push(a)});return b};m.nd=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};m.od=function(a){if(pd){pd=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.qd(c))&&c!=b.hostname)throw pd=!0,Error();}}return a.match(rd)};m.sd=function(a){return a?(0,window.decodeURI)(a):a};m.qd=function(a){return m.sd(m.od(a)[3]||null)};
m.td=function(a){a=m.od(a);return m.nd(null,null,null,null,a[5],a[6],a[7])};m.ud=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};m.vd=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.vd(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.xa(b))};var wd=function(a,b){for(var c in b)m.vd(c,b[c],a);return a};m.xd=function(a){a=wd([],a);a[0]="";return a.join("")};
m.yd=function(a,b){return m.ud(wd([a],b))};m.zd=function(a,b,c){a&&(c?a&&(a=m.Uc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.ed(a).body.appendChild(a)):Ad(a,b))};var Ad=function(a,b){var c=new window.Image,d=""+Bd++;Cd[d]=c;c.onload=c.onerror=function(){b&&Cd[d]&&b();delete Cd[d]};c.src=a;c=eval("null")};m.Dd=function(a,b){this.version=a;this.args=b};m.Ed=function(a,b){this.j=a;this.Ae=b};
m.Fd=function(a,b){var c=m.Gd();return c?c.publish.call(c,a.toString(),a,b):!1};m.Gd=function(){return m.n("yt.pubsub2.instance_")};var Hd=function(a){m.Dd.call(this,1,arguments)};m.Id=function(a,b,c){Jd(c)[a]=b||(0,m.G)();b||Kd(a);m.w("CSI_LOG_ON_TICK")&&Ld(!1,c)};var Md=function(a,b){Nd(void 0).yt_sts=a;m.Id("_start",b,void 0)};var Od=function(a){Pd(a);Qd();m.l("yt.timing.pingSent_",!1,void 0)};
var Rd=function(a){a=Jd(a);if(a.aft)return a.aft;for(var b=m.w("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
var Sd=function(a,b){var c=Td(b).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};var Ud=function(a){return Math.round(Vd.timing.navigationStart+a)};
var Wd=function(a){var b=window.location.protocol,c=Vd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Ud(d.startTime),a.wfce=Ud(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Ud(c.startTime),a.wffe=Ud(c.responseEnd))};
var Xd=function(a){var b=Jd(a),c=Td(a).span,d=Nd(a),e=m.n("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Yd(e),Od(a)}else{e={v:2,s:m.w("CSI_SERVICE_NAME","youtube"),action:m.w("TIMING_ACTION")};if(Vd.now&&Vd.timing){var f=Vd.timing.navigationStart+Vd.now(),f=Math.round((0,m.G)()-f);d.yt_hrd=f}var f=m.w("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Vd.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=
h;d.h5jse&&(f=window.location.protocol+m.n("ytplayer.config.assets.js"),(f=Vd.getEntriesByName?Vd.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft=Rd(a);f=b._start;if("cold"==d.yt_lt){k||(k=Vd.timing||{});var p;a:if(p=k,p.msFirstPaint)p=Math.max(0,p.msFirstPaint);else{var v=window.chrome;if(v&&(v=v.loadTimes,m.na(v))){var v=v(),z=1E3*Math.min(v.requestTime||window.Infinity,v.startLoadTime||window.Infinity),z=window.Infinity===z?0:p.navigationStart-z;p=Math.max(0,
Math.round(1E3*v.firstPaintTime+z)||0);break a}p=0}0<p&&p>f&&(b.fpt=p);Sd(k,a);m.w("EXP_WEBFONT_ENABLED")&&Vd.getEntriesByType&&Wd(b)}d.p=m.w("CLIENT_PROTOCOL")||"unknown";d.t=m.w("CLIENT_TRANSPORT")||"unknown";for(var N in d)"_"!=N.charAt(0)&&(e[N]=d[N]);m.w("CSI_MORE")&&(b.ps=(0,m.G)());d={};k=[];for(var ba in b)"_"!=ba.charAt(0)&&(p=Math.max(Math.round(b[ba]-f),0),d[ba]=p,k.push(ba+"."+p));e.rt=k.join(",");b={};ba=[];for(var la in c)"_"!=la.charAt(0)&&(b[la]=c[la],ba.push(la+"."+c[la]));e.it=ba.join(",");
(c=m.n("ytdebug.logTiming"))&&c(e,d,b);Od(a);m.w("EXP_DEFER_CSI_PING")?(Zd(),m.l("yt.timing.deferredPingArgs_",e,void 0),a=m.x(Zd,0),m.l("yt.timing.deferredPingTimer_",a,void 0)):Yd(e);m.Fd($d,new Hd(d.aft+(h||0)))}};var Ld=function(a,b){var c=m.w("TIMING_ACTION"),d=Jd(b);if(c&&d._start&&Rd(b)){var c=!0,e=m.w("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,h=e.length;f<h;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&Xd(b)}};var ae=function(a){m.w("CSI_LOG_ON_TICK")||Ld(!1,a)};
var Yd=function(a){m.w("EXP_DEFER_CSI_PING")&&(m.fb(m.n("yt.timing.deferredPingTimer_")),m.l("yt.timing.deferredPingArgs_",null,void 0));var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.zd(b+"?"+c.substring(1));m.l("yt.timing.pingSent_",!0,void 0)};var Zd=function(a){if(m.w("EXP_DEFER_CSI_PING")){var b=m.n("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Yd(b))}};var Jd=function(a){return Td(a).tick};var Nd=function(a){return Td(a).info};
var Td=function(a){return m.n("ytcsi."+(a||"")+"data_")||Pd(a)};var Pd=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};var be=function(a){m.w("CSI_MORE")&&!m.n("yt.timing.pingSent_")&&(Nd(void 0).ap=1,Nd(void 0).yt_fss=a,Xd())};var ce=function(a){a=m.de(a);return m.ee(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
m.ee=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};m.de=function(a){a=(0,m.fe)(a);return null===a?null:a.split(".").reverse()};m.ge=function(a,b){m.zd("/gen_204?"+a,b)};m.he=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};m.H=function(a,b){return a.classList?a.classList.contains(b):m.Ra(m.he(a),b)};m.I=function(a,b){a.classList?a.classList.add(b):m.H(a,b)||(a.className+=0<a.className.length?" "+b:b)};
m.J=function(a,b){a.classList?a.classList.remove(b):m.H(a,b)&&(a.className=(0,m.ie)(m.he(a),function(a){return a!=b}).join(" "))};m.je=function(a,b,c){c?m.I(a,b):m.J(a,b)};
var ke=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.Ib(le);this.assets=a.assets||{};this.attrs=a.attrs||m.Ib(me);this.params=a.params||m.Ib(ne);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.oe=function(a){a instanceof ke||(a=new ke(a));return a};var pe=function(){return null!=m.qe};
m.re=function(){return m.qe?m.qe.invoke():null};m.se=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.A)(a.childNodes,function(a){b.appendChild(m.se(a))}):b.innerHTML=a.innerHTML;return b};
m.te=function(a){if(a=a||window.event){for(var b in a)b in ue||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.Va=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Rk=a.pageX;this.Sk=a.pageY}};m.ve=function(a,b,c,d){return m.Fb(m.we,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.ve(a,b,c,d);if(e)return e;var e=++xe.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.te(d);if(!m.fd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.te(b);b.currentTarget=a;return c.call(a,b)};h=m.db(h);m.we[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.L=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.A)(a,function(a){if(a in m.we){var c=m.we[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete m.we[a]}}))};
m.ye=function(a){a=a||window.event;a=a.target||a.srcElement;3==a.nodeType&&(a=a.parentNode);return a};m.ze=function(a){this.j=a};m.Ae=function(a){a=(a.j.cookie||"").split(m.Be);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};m.Ce=function(a,b,c,d){m.De.set(""+a,b,c,"/",d||"youtube.com")};m.Ee=function(a,b){return m.De.get(""+a,b)};
m.Fe=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.n("_lact",window)){if(m.w("EXP_LACT_TEMPDATA")){var c=(0,window.parseInt)(m.w("LACT"),10),c=(0,window.isFinite)(c)?(0,m.G)()-Math.max(c,0):-1;m.l("_lact",c,window);-1==c&&Ge()}else a&&b?(c=m.Ee("ACTIVITY","-1"),m.l("_lact",(0,window.parseInt)(c,10),window)):(m.l("_lact",-1,window),Ge());m.K(window.document,"keydown",Ge);m.K(window.document,"keyup",Ge);m.K(window.document,"mousedown",Ge);m.K(window.document,"mouseup",Ge);m.w("EXP_LACT_MOUSE")&&
m.y("page-mouse",Ge);m.w("EXP_LACT_SCROLL")&&m.y("page-scroll",Ge);m.w("EXP_LACT_RESIZE")&&m.y("page-resize",Ge)}};var Ge=function(){var a=m.n("_lact",window);null==a&&(m.Fe(),a=m.n("_lact",window));var b=(0,m.G)();m.l("_lact",b,window);m.w("EXP_LACT_TEMPDATA")||m.n("_lactCookie",window)&&1E3<=b-a&&m.Ce("ACTIVITY",""+b,-1);m.B("USER_ACTIVE")};m.He=function(){var a=m.n("_lact",window);return null==a?-1:Math.max((0,m.G)()-a,0)};
m.Ie=function(a,b,c){var d=m.qd(a);if(d==m.qd(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.td(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Je(a,b,c)):Je(a,b)};var Je=function(a,b,c){a=m.w("SMALLER_SESSION_TEMPDATA_NAME")?"ST-"+Ma(a).toString(36):"s_tempdata-"+Ma(a);c=c||5;b=b?m.xd(b):"";m.Ce(a,b,c)};m.Ke=function(a,b,c){var d=c||"";c=window.location;a=m.yd(a,b||{})+d;a=a instanceof m.Tb?a:m.Wb(a);c.href=m.Vb(a)};
m.Le=function(a,b){b&&m.Ie(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):m.Ke(a)};m.Me=function(a,b,c){var d=m.w("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.Ie(a,b);if(c)return!1;m.Le(a);return!0};var Ne=function(a,b,c){this.A=c;this.l=a;this.n=b;this.k=0;this.j=null};var Oe=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Pe=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!m.xc("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Ac()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.da(c.next)){c=c.next;var a=c.Bm;c.Bm=null;a()}};return function(a){d.next={Bm:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var Qe=function(){this.k=this.j=null};var Re=function(){this.next=this.scope=this.Id=null};var Se=function(a,b){Te||Ue();Ve||(Te(),Ve=!0);We.add(a,b)};
var Ue=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();Te=function(){a.then(Xe)}}else Te=function(){var a=Xe;!m.na(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?(Ye||(Ye=Pe()),Ye(a)):m.ea.setImmediate(a)}};var Xe=function(){for(var a=null;a=We.remove();){try{a.Id.call(a.scope)}catch(b){Oe(b)}Ze.put(a)}Ve=!1};m.$e=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
m.af=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.bf=function(a,b){this.j=0;this.C=void 0;this.n=this.k=this.l=null;this.A=this.B=!1;if(a==m.cf)df(this,2,b);else try{var c=this;a.call(b,function(a){df(c,2,a)},function(a){df(c,3,a)})}catch(d){df(this,3,d)}};var ef=function(){this.next=this.context=this.k=this.l=this.j=null;this.n=!1};var ff=function(a,b,c){var d=gf.get();d.l=a;d.k=b;d.context=c;return d};m.cf=function(){};
m.hf=function(a,b,c,d){a instanceof m.bf?jf(a,ff(b||m.fa,c||null,d)):a.then(b,c,d)};var kf=function(a,b){if(0==a.j)if(a.l){var c=a.l;if(c.k){for(var d=0,e=null,f=null,h=c.k;h&&(h.n||(d++,h.j==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.j&&1==d?kf(c,b):(f?(d=f,d.next==c.n&&(c.n=d),d.next=d.next.next):nf(c),of(c,e,3,b)))}a.l=null}else df(a,3,b)};var jf=function(a,b){a.k||2!=a.j&&3!=a.j||pf(a);a.n?a.n.next=b:a.k=b;a.n=b};
m.qf=function(a,b,c,d){var e=ff(null,null,null);e.j=new m.bf(function(a,h){e.l=b?function(c){try{var e=b.call(d,c);a(e)}catch(v){h(v)}}:a;e.k=c?function(b){try{var e=c.call(d,b);!m.da(e)&&b instanceof rf?h(b):a(e)}catch(v){h(v)}}:h});e.j.l=a;jf(a,e);return e.j};
var df=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.af(c)){a.j=1;m.hf(c,a.J,a.F,a);return}if(m.oa(c))try{var d=c.then;if(m.na(d)){sf(a,c,d);return}}catch(e){b=3,c=e}}a.C=c;a.j=b;a.l=null;pf(a);3!=b||c instanceof rf||tf(a,c)}};var sf=function(a,b,c){function d(b){f||(f=!0,a.F(b))}function e(b){f||(f=!0,a.J(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var pf=function(a){a.B||(a.B=!0,Se(a.P,a))};
var nf=function(a){var b=null;a.k&&(b=a.k,a.k=b.next,b.next=null);a.k||(a.n=null);return b};var of=function(a,b,c,d){b.j&&(b.j.l=null);if(2==c)b.l.call(b.context,d);else if(null!=b.k){if(!b.n)for(;a&&a.A;a=a.l)a.A=!1;b.k.call(b.context,d)}gf.put(b)};var tf=function(a,b){a.A=!0;Se(function(){a.A&&uf.call(null,b)})};var rf=function(a){m.wa.call(this,a)};var vf=function(a){this.j=a;a.then((0,m.q)(function(){},this))};
var wf=function(a,b,c,d){for(var e=Array(arguments.length-3),f=3;f<arguments.length;f++)e[f-3]=arguments[f];f=xf(a,b,c).then(function(a){return a.apply(this,e)});return new vf(f)};
var xf=function(a,b,c){var d="https://www.gstatic.com/feedback/js/help/"+(a&&"prod"!=a&&"canary"!=a?"nonprod":"prod")+"/"+b;if(a=yf[c])return a;a=(a=m.n(c))?new m.bf(m.cf,a):(new m.bf(function(a,b){var c=window.document.createElement("script");c.async=!0;c.src=d;c.onload=c.onreadystatechange=function(){c.readyState&&"loaded"!=c.readyState&&"complete"!=c.readyState||a()};c.onerror=b;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(c)})).then(function(){var a=m.n(c);
if(!a)throw Error("Failed to load "+c+" from "+d);return a});return yf[c]=a};var zf=function(a,b,c){a.j.then(function(a){var e=a[b];if(!e)throw Error("Method not found: "+b);return e.apply(a,c)})};var Af=function(a){this.j=a};
var Bf=function(a,b){var c=b||{},c=wf("prod","service/lazy.min.js","help.service.Lazy.create",a,{apiKey:c.qf||c.apiKey,environment:c.Bf||c.environment,helpCenterPath:c.ZE||c.helpCenterPath,locale:c.locale||c.locale,productData:c.jF||c.productData,receiverUri:c.kF||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window});return new Af(c)};var Cf=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Df=function(a){return(a=a.exec(m.yc))?a[1]:""};
m.Ef=function(a){return 0<=m.Ja(Ff,a)};var Gf=function(){return m.D?m.Ef("8"):m.Hf?m.Ef("15"):m.If?m.Ef("5"):m.Jf};
var Kf=function(){this.l=this.k=this.j=0;this.n="";var a=m.n("window.navigator.plugins"),b=m.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.n=b;b=a;this.j=b[0];this.k=b[1];this.l=b[2];if(0>=this.j){var h,k,p,v;if(m.Lf)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(z){h=null}else p=window.document.body,v=window.document.createElement("object"),v.setAttribute("type","application/x-shockwave-flash"),h=p.appendChild(v);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(N){k=""}p&&v&&p.removeChild(v);(h=k||"")?(h=h.split(" ")[1].split(","),
h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.j=h[0];this.k=h[1];this.l=h[2]}};var Mf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.k>b[1]||a.j==b[0]&&a.k==b[1]&&a.l>=b[2]};
var Nf=function(a){return-1<a.n.indexOf("Gnash")&&-1==a.n.indexOf("AVM2")||9==a.j&&1==a.k||9==a.j&&0==a.k&&1==a.l?!1:9<=a.j};var Of=function(a){return m.Pf?!Mf(a,11,2):m.Qf?!Mf(a,11,3):!Nf(a)};m.Rf=function(){return m.Gc?"Webkit":m.Fc?"Moz":m.D?"ms":m.Sf?"O":null};m.Tf=function(){return m.Gc?"-webkit":m.Fc?"-moz":m.D?"-ms":m.Sf?"-o":null};m.Uf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.Vf=function(a,b){return a&&b?b instanceof m.Uf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.Wf=function(a,b){var c=Xf[b];if(!c){var d=m.Na(b),c=d;void 0===a.style[d]&&(d=m.Rf()+m.Oa(d),void 0!==a.style[d]&&(c=d));Xf[b]=c}return c};m.Yf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.Zf=function(a,b){a.style.height=m.Yf(b,!0)};m.$f=function(a,b){a.style.display=b?"":"none"};
m.ag=function(a,b){(a=m.E(a))&&a.style&&(m.$f(a,b),m.je(a,"hid",!b))};m.M=function(a){(0,m.A)(arguments,function(a){m.ag(a,!0)})};
var bg=function(a,b){var c=m.w("FEEDBACK_LOCALE_LANGUAGE"),d=m.cg,e=m.w("FEEDBACK_LOCALE_EXTRAS",{});a?m.Jb(d,a):m.Jb(d,e);try{var f,h=m.n("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=Kf.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(p){}b&&m.Jb(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var dg=function(){var a=m.w("SESSION_INDEX"),b=m.w("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.eg=function(a,b){try{var c=(a||"59")+"",d=bg(b),e=dg();Bf(c,d).l(e);return!1}catch(f){return!0}};
m.fg=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=bg(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.Jb(a,dg());try{var p=Bf(b,d);if(e&&!gg)try{p.k(a),gg=!0}catch(v){}p.n(a);return!1}catch(z){return!0}};m.hg=function(a,b,c,d){return m.fg(void 0,d,b,c,void 0,void 0,void 0,a)};m.ig=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.af=!1;this.Wp=!0};
m.jg=function(a,b){m.ig.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.Va=this.state=null;a&&this.init(a,b)};m.kg=function(a){return!(!a||!a[m.lg])};var mg=function(a,b,c,d,e){this.We=a;this.j=null;this.src=b;this.type=c;this.Dh=!!d;this.Vc=e;this.key=++ng;this.Xf=this.Bh=!1};
var og=function(a){a.Xf=!0;a.We=null;a.j=null;a.src=null;a.Vc=null};m.pg=function(a){this.src=a;this.j={};this.k=0};m.qg=function(a,b){var c=b.type;if(!(c in a.j))return!1;var d=m.Ta(a.j[c],b);d&&(og(b),0==a.j[c].length&&(delete a.j[c],a.k--));return d};m.rg=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Xf&&f.We==b&&f.Dh==!!c&&f.Vc==d)return e}return-1};
m.sg=function(a,b,c,d,e){if(m.ia(b)){for(var f=0;f<b.length;f++)m.sg(a,b[f],c,d,e);return null}c=m.tg(c);return m.kg(a)?a.Q(b,c,d,e):m.ug(a,b,c,!1,d,e)};m.ug=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=!!e,k=m.vg(a);k||(a[wg]=k=new m.pg(a));c=k.add(b,c,d,e,f);if(c.j)return c;d=xg();c.j=d;d.src=a;d.We=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(yg(b.toString()),d);zg++;return c};
var xg=function(){var a=Ag,b=Bg?function(c){return a.call(b.src,b.We,c)}:function(c){c=a.call(b.src,b.We,c);if(!c)return c};return b};m.Cg=function(a){if(m.ma(a)||!a||a.Xf)return!1;var b=a.src;if(m.kg(b))return b.Hq(a);var c=a.type,d=a.j;b.removeEventListener?b.removeEventListener(c,d,a.Dh):b.detachEvent&&b.detachEvent(yg(c),d);zg--;(c=m.vg(b))?(m.qg(c,a),0==c.k&&(c.src=null,b[wg]=null)):og(a);return!0};var yg=function(a){return a in Dg?Dg[a]:Dg[a]="on"+a};
var Eg=function(a,b,c,d){var e=!0;if(a=m.vg(a))if(b=a.j[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Dh==c&&!f.Xf&&(f=Fg(f,d),e=e&&!1!==f)}return e};var Fg=function(a,b){var c=a.We,d=a.Vc||a.src;a.Bh&&m.Cg(a);return c.call(d,b)};
var Ag=function(a,b){if(a.Xf)return!0;if(!Bg){var c=b||m.n("window.event"),d=new m.jg(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.af&&0<=k;k--){d.currentTarget=c[k];var p=Eg(c[k],f,!0,d),e=e&&p}for(k=0;!d.af&&k<c.length;k++)d.currentTarget=c[k],p=Eg(c[k],f,!1,d),e=e&&p}return e}return Fg(a,
new m.jg(b,this))};m.vg=function(a){a=a[wg];return a instanceof m.pg?a:null};m.tg=function(a){if(m.na(a))return a;a[Gg]||(a[Gg]=function(b){return a.handleEvent(b)});return a[Gg]};m.Hg=function(){var a=m.Ee("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Ig[d]=c.toString())}};var Jg=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
var Kg=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Lg=function(a){a=void 0!==m.Ig[a]?m.Ig[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Mg=function(a,b){return!!((m.Lg("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Ng=function(a,b,c){if(b){a=m.ka(a)?m.Nc(a):a;c=m.oe(c);var d=m.Ib(c.attrs);d.tabindex=0;var e=m.Ib(c.params);e.flashvars=m.xd(c.args);if(m.Lf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Og=function(a,b){a=m.ka(a)?m.Nc(a):a;b=m.oe(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Kf.getInstance();Mf(c,b.minVersion)?(c=Pg(b,c),Ng(a,c,b)):Qg(a,b,c)};
var Rg=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.oe(a);var d=!!b,e=m.E(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);ce(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Kf.getInstance();if(Mf(h,a.minVersion)){var k=Pg(a,h),p="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(p=e.getAttribute("src")||e.movie);(p!=k||d)&&Ng(f,k,a);Of(h)&&Sg()}else Qg(f,a,h);c&&c()}else m.x(function(){Rg(a,
b,c)},50)}};var Qg=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.kb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Pg=function(a,b){var c;(c=Nf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Mf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
var Sg=function(){var a=m.E("flash10-promo-div"),b=m.Mg(m.Hg.getInstance(),107);a&&!b&&m.M(a)};m.Tg=function(a,b){var c=a.match(Ug);window.spf.style.load(a,c?c[1]:"",b)};var Vg=function(){if(2.2==Wg)return!0;var a;a=m.n("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};
var Xg=function(){};m.Yg=function(){};m.Zg=function(a){this.j=a};m.$g=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};var ah=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};
m.bh=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.ch=function(a){return(new m.dh(void 0)).yb(a)};m.dh=function(a){this.j=a};
var eh=function(a,b,c){switch(typeof b){case "string":fh(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],eh(a,a.j?a.j.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),fh(f,c),c.push(":"),eh(a,a.j?a.j.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var fh=function(a,b){b.push('"',a.replace(gh,function(a){if(a in hh)return hh[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return hh[a]=e+b.toString(16)}),'"')};m.ih=function(a){this.j=a};var jh=function(a){this.j=a};var kh=function(a){this.data=a};var lh=function(a){return!m.da(a)||a instanceof kh?a:new kh(a)};
m.mh=function(a){this.j=a};m.nh=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.G)()||!!b&&b>(0,m.G)()};m.oh=function(a){this.j=a};m.ph=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.G)()+1E3*d:0;if((d=d?m.qh:m.rh)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.sh=function(a){if(!m.rh&&!m.qh||!window.JSON)return null;var b;try{b=m.rh.get(a)}catch(c){}if(!m.ka(b))try{b=m.qh.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var th=function(){var a={volume:100,muted:!1},b=m.sh("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.vc(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var uh=function(a,b){m.u.call(this);this.n=this.B=a;this.S=b;this.P=!1;this.k={};this.Za=this.O=null;this.$=new m.$a;m.Xa(this,this.$);this.A={};this.J=this.bb=this.l=this.Eb=this.j=null;this.Ea=!1;this.R=this.F=this.vb=this.C=null;this.hb={};this.ud=["onReady"];this.lb=[];this.Lb=null;this.kc=0;this.Oa={};vh(this);this.rd("onVolumeChange",(0,m.q)(this.yy,this));this.rd("onError",(0,m.q)(this.wy,this));this.rd("onTabOrderChange",(0,m.q)(this.xs,this));this.rd("onTabAnnounce",(0,m.q)(this.LA,this));
this.rd("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.zy,this));this.rd("WATCH_LATER_VIDEO_REMOVED",(0,m.q)(this.Ay,this));this.rd("onMouseWheelCapture",(0,m.q)(this.my,this));this.rd("onMouseWheelRelease",(0,m.q)(this.ny,this));this.rd("onMouseMoveCapture",(0,m.q)(this.ky,this));this.ub=!1;this.Kc=m.Jf||m.Hf;this.Qa=this.U=null;m.sg(this.B,"mousewheel",this.hp,!1,this);m.sg(this.B,"wheel",this.hp,!1,this)};
var wh=function(a,b){a.Eb=b;a.j=b.clone();a.l=a.j.attrs.id||a.l;"video-player"==a.l&&(a.l=a.S,a.j.attrs.id=a.S);a.n.id==a.l&&(a.l=a.l+"-player",a.j.attrs.id=a.l);a.j.args.enablejsapi="1";a.j.args.playerapiid=a.S;a.bb||(a.bb=xh(a,a.j.args.jsapicallback||"onYouTubePlayerReady"));a.j.args.jsapicallback=null;var c=a.j.attrs.width;c&&(a.n.style.width=m.Yf(Number(c)||c,!0));(c=a.j.attrs.height)&&m.Zf(a.n,Number(c)||c);a.n.style.overflow="hidden"};
var yh=function(a){a.j.loaded||(a.j.loaded=!0,"0"!=a.j.args.autoplay?a.k.loadVideoByPlayerVars(a.j.args):a.k.cueVideoByPlayerVars(a.j.args))};var zh=function(a){if(!m.da(a.j.disable.flash)){var b=a.j.disable,c;c=Mf(Kf.getInstance(),a.j.minVersion);b.flash=!c}return!a.j.disable.flash};
var Ah=function(a){var b=Bh(a);b&&b.stopVideo&&b.stopVideo();if(zh(a)){var c=a.j;b&&b.getUpdatedConfigurationData&&(c=m.oe(b.getUpdatedConfigurationData()));c.args.autoplay=1;c.args.html5_unavailable="1";wh(a,c);Ch(a,"flash")}};
var Ch=function(a,b){if(!a.Na()){if(!b){var c;if(!(c=!a.j.html5&&zh(a))){if(!m.da(a.j.disable.html5)){if(c=Vg())c=Dh(a)||a.j.assets.js;a.j.disable.html5=!c;c||(a.j.args.html5_unavailable="1")}c=!!a.j.disable.html5}b=c?zh(a)?"flash":"unsupported":"html5"}("flash"==b?a.dB:"html5"==b?a.eB:a.fB).call(a)}};var Dh=function(a){var b=!0,c=Bh(a);c&&a.j&&(a=a.j,b=m.C(c,"version")==a.assets.js);return b&&!!m.n("yt.player.Application.create")};
var Bh=function(a){var b=m.E(a.l);!b&&a.n&&a.n.querySelector&&(b=a.n.querySelector("#"+a.l));return b};var Eh=function(a,b,c){var d=b[c];return function(){try{return a.Lb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Lb=e,m.hb(e,"WARNING"))}}};
var vh=function(a){a.P=!1;if(a.Za)for(var b in a.A)a.Za(b,a.A[b]);for(var c in a.Oa)m.fb((0,window.parseInt)(c,10));a.Oa={};a.O=null;a.Za=null;for(var d in a.k)a.k[d]=null;a.k.addEventListener=(0,m.q)(a.rd,a);a.k.removeEventListener=(0,m.q)(a.cA,a);a.k.destroy=(0,m.q)(a.dispose,a);a.k.getLastError=(0,m.q)(a.Ys,a);a.k.getPlayerType=(0,m.q)(a.Zs,a);a.k.getCurrentVideoConfig=(0,m.q)(a.Xs,a);a.k.loadNewVideoConfig=(0,m.q)(a.Sl,a);a.k.isReady=(0,m.q)(a.rB,a)};
var xh=function(a,b){var c=b;if("string"==typeof b){if(a.hb[b])return a.hb[b];c=function(){var a=m.n(b);a&&a.apply(m.ea,arguments)};a.hb[b]=c}return c?c:null};var Fh=function(a,b){var c="ytPlayer"+b+a.S;a.A[b]=c;m.ea[c]=function(c){var e=m.x(function(){a.Na()||(a.$.W(b,c),m.Gb(a.Oa,e.toString()))},0);m.Hb(a.Oa,e.toString(),!0)};return c};var Gh=function(a){return(a=Bh(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Hh=function(a){m.Id("dcp");a.cancel();vh(a);a.J=null;a.j&&(a.j.loaded=!1);var b=Bh(a);"html5"==Gh(a)?a.vb=b:b&&b.destroy&&b.destroy();m.Zc(a.B);m.L(a.lb);a.lb.length=0;a.F=null;a.R=null};m.Ih=function(a,b){a=m.ka(a)?m.Nc(a):a;b=m.oe(b);var c=Jh+"_"+m.pa(a),d=Kh[c];if(d)return d.Sl(b),d.k;d=new uh(a,c);Kh[c]=d;m.B("player-added",d.k);m.Ya(d,m.r(Lh,d));m.x(function(){d.Sl(b)},0);return d.k};var Mh=function(){for(var a in Kh){var b=Kh[a];b&&b.cancel()}};
m.Nh=function(a){if(a=m.E(a))a=Jh+"_"+m.pa(a),(a=Kh[a])&&a.dispose()};var Lh=function(a){Kh[a.getId()]=null};m.Oh=function(a){a=m.E(a);if(!a)return null;var b=Jh+"_"+m.pa(a),c=Kh[b];c||(c=new uh(a,b),Kh[b]=c);return c.k};m.Ph=function(){return m.H(m.E("page-container"),"remote-connected")};
var Qh=function(){m.l("yt.abuse.botguardInitialized",pe,void 0);m.l("yt.abuse.invokeBotguard",m.re,void 0);m.l("yt.player.exports.navigate",m.Me,void 0);m.l("yt.player.embed",m.Ih,void 0);m.l("yt.player.destroy",m.Nh,void 0);m.l("yt.player.cancelAll",Mh,void 0);m.l("yt.player.getPlayerByElement",m.Oh,void 0);m.l("yt.player.exports.feedbackStart",m.eg,void 0);m.l("yt.player.exports.feedbackShowArticle",m.hg,void 0);m.l("yt.util.activity.init",m.Fe,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.He,void 0);m.l("yt.util.activity.setTimestamp",Ge,void 0);var a=m.n("ytplayer.config");Rh(a);m.n("ytspf.enabled")&&(Sh=m.eb(Th,5E3),(a=m.Uh())?(a.addEventListener("onReady",Th),a.addEventListener("onStateChange",Th)):Vh("unable to init PP monitor"))};
var Rh=function(a){Mh();if(a=a||null){var b=m.Uh(),c=!0,d=m.Wh;m.Wh=null;b&&b.getVideoData&&d&&(c=b.getVideoData(),c=!!d.fullscreen||c.video_id!=a.args.video_id||c.list!=a.args.list||c.video_id!=d.videoId||c.list!=d.listId);c?(Xh="",m.Ih("player-api",a)):b.playVideo();a=m.oe(a);a.loaded=!0}Th();m.l("ytplayer.config",a,void 0)};m.Uh=function(){var a=m.n("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Th=function(){var a=m.Uh();if(a){var b;b=m.E("player");b=!b||m.H(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==m.w("PAGE_NAME"),e=m.Ph();!c||d||e||(Vh("PP playing off watch (paused)"),a.pauseVideo());b&&d?Vh("PP off-screen on watch"):b||d||Vh("PP !off-screen off watch")}};var Vh=function(a){var b=m.w("PAGE_NAME");b&&(b=[b,Xh,m.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.hb(Error(a),"WARNING"))};
var Yh=function(){m.Id("ol");Zh("init");var a=m.w("PAGE_NAME");a&&Zh("init-"+a);ae()};var Zh=function(a){m.sb()?$h.push(m.tb(m.r(m.rb,a),0)):m.B(a)};var ai=function(){m.wb($h);$h.length=0;var a=m.w("PAGE_NAME");a&&m.rb("dispose-"+a);m.rb("dispose")};var bi=function(){Yh()};var ci=function(){m.w("TIMING_REPORT_ON_UNLOAD")&&Ld(!0);be("u");Zd("u");ai()};
var di=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,p=f.length;k<p;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.hb(e))};var ei=function(){fi=1;gi=0;m.w("TIMING_REPORT_ON_UNLOAD")&&Ld(!0);be("n");Zd("n");Od();m.w("CSI_TRACK_ON_BEGIN")&&Md("nb");Kd("mark_navigation_requested");hi(ii);m.rb("navigate")};
var ji=function(a){a=a.detail.part||a.detail.partial;m.Id("nc"+gi);++gi;var b=1==fi;fi=2;b?(hi(ki),li()):hi(mi);(a=a.data&&a.data.swfcfg)&&ni(a)};var oi=function(){};var pi=function(a){a=a.detail.response;var b=1==fi;fi=3;b&&(hi(qi),li());(a=a.data&&a.data.swfcfg)&&ni(a)};
var ri=function(a){m.Id("nd");a=a.detail.response;m.si=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Nd(void 0).yt_nav=b;Md("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Nd(void 0).srt=b;b=a.spfCached?"hot":"warm";Nd(void 0).yt_lt=b;b=+!!a.spfPrefetched;Nd(void 0).yt_pft=b;b=a.responseStart-a.fetchStart;Td(void 0).span.req=b;"redirectStart"in a&&Sd(a);hi(ti);window.document.getElementById("content").style.height="";Yh();fi=0};
var ui=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.hb(a)};var vi=function(a){a=m.xd({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.ge(a)};var wi=function(){xi()};var yi=function(){};
var li=function(){m.w("USE_SPF_SCROLL_POSITION")||window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");ai();for(var b in m.cb)delete m.cb[b];m.l("ytplayer.config",null,void 0);if((a=m.Uh())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Xh=a,(a=m.E("movie_player"))&&a.stopVideo?(a.stopVideo(),Xh="recovered"):Xh="missing2"}else Xh="missing";Th()};var ni=function(a){"cfg"in Jd(void 0)||m.Id("cfg");Rh(a)};
var hi=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));m.vb(zi);zi=m.ub(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";m.fb(Ai);Ai=m.x(function(){b.className=e},c)},0)};
var xi=function(){var a=ti[0]+50;m.fb(Ai);Ai=m.x(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var Bi=function(){m.xb.call(this,"www/base");this.l=0};var Ci=function(a){(a=a.detail.name)&&Bb(a)};m.ca=[];m.Di=m.Di||{};m.ea=this;qa="closure_uid_"+(1E9*Math.random()>>>0);ra=0;m.G=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};ua[" "]=m.fa;m.t(m.wa,Error);m.wa.prototype.name="CustomError";var Aa,Ba,Ca,Da,Ea,Fa,za;m.Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};Aa=/&/g;Ba=/</g;Ca=/>/g;Da=/"/g;Ea=/'/g;Fa=/\x00/g;za=/[\x00&<>"']/;m.Ei=2147483648*Math.random()|0;m.Va=Array.prototype;m.Sa=m.Va.indexOf?function(a,b,c){return m.Va.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Fi=m.Va.lastIndexOf?function(a,b,c){return m.Va.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.A=m.Va.forEach?function(a,b,c){m.Va.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.ie=m.Va.filter?function(a,b,c){return m.Va.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.ka(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};m.Gi=m.Va.map?function(a,b,c){return m.Va.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.ka(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Hi=m.Va.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Va.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.A)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Ii=m.Va.some?function(a,b,c){return m.Va.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Ji=m.Va.every?function(a,b,c){return m.Va.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.gb=!1;m.u.prototype.Na=function(){return this.gb};m.u.prototype.dispose=function(){this.gb||(this.gb=!0,this.L())};m.u.prototype.L=function(){if(this.Ya)for(;this.Ya.length;)this.Ya.shift()()};m.t(m.$a,m.u);m.g=m.$a.prototype;m.g.In=1;m.g.Qi=0;m.g.subscribe=function(a,b,c){var d=this.xc[a];d||(d=this.xc[a]=[]);var e=this.In;this.j[e]=a;this.j[e+1]=b;this.j[e+2]=c;this.In=e+3;d.push(e);return e};m.g.hf=function(a,b,c){if(a=this.xc[a]){var d=this.j;if(a=m.Pa(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.yc(a)}return!1};
m.g.yc=function(a){if(0!=this.Qi)return this.k||(this.k=[]),this.k.push(a),!1;var b=this.j[a];if(b){var c=this.xc[b];c&&m.Ta(c,a);delete this.j[a];delete this.j[a+1];delete this.j[a+2]}return!!b};m.g.W=function(a,b){var c=this.xc[a];if(c){this.Qi++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.j[h+1].apply(this.j[h+2],d)}this.Qi--;if(this.k&&0==this.Qi)for(;c=this.k.pop();)this.yc(c);return 0!=e}return!1};
m.g.clear=function(a){if(a){var b=this.xc[a];b&&((0,m.A)(b,this.yc,this),delete this.xc[a])}else this.j.length=0,this.xc={}};m.g.Wa=m.aa(3);m.g.L=function(){m.$a.D.L.call(this);delete this.j;delete this.xc;delete this.k};m.cb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};m.l("yt.config_",m.cb,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.jb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.jb,void 0);m.Lf="Microsoft Internet Explorer"==window.navigator.appName;var Ki=m.n("yt.pubsub.instance_")||new m.$a;m.$a.prototype.subscribe=m.$a.prototype.subscribe;m.$a.prototype.unsubscribeByKey=m.$a.prototype.yc;m.$a.prototype.publish=m.$a.prototype.W;m.$a.prototype.clear=m.$a.prototype.clear;m.l("yt.pubsub.instance_",Ki,void 0);var nb=m.n("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",nb,void 0);var pb=m.n("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",pb,void 0);var ob=m.n("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",ob,void 0);var mb=m.n("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",mb,void 0);m.g=m.xb.prototype;m.g.jA=function(){2==this.j||this.init()};m.g.enable=function(){this.j=1;(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.jA,this),this.subscribe("dispose-"+a,this.dispose,this),m.w("PAGE_NAME")==a&&m.yb(this))},this)};m.g.init=function(){m.vb(this.k);this.j=2;this.B&&this.B()};m.g.dispose=function(){this.j=3;m.vb(this.k);this.A&&this.A()};m.g.disable=function(){this.j=4;this.clear();try{this.dispose()}catch(a){m.hb(a)}};
m.g.subscribe=function(a,b,c){a=m.y(a,b,c);this.n.push(a);return a};m.g.clear=function(){m.qb(this.n);this.n=[]};var Ab=m.n("yt.modules.registry_")||{};m.l("yt.modules.registry_",Ab,void 0);var Kb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var mc=Lb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Li=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Mi=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Mb.prototype.Se=!0;m.Mb.prototype.Ie=function(){return this.j};m.Mb.prototype.toString=function(){return"Const{"+this.j+"}"};var Nb={};m.Pb.prototype.Se=!0;var Qb={};m.Pb.prototype.Ie=function(){return this.j};var kc=Sb(""),jc=/^[-,."'%_!# a-zA-Z0-9]+$/;m.Tb.prototype.Se=!0;m.Tb.prototype.Ie=function(){return this.j};m.Tb.prototype.rk=!0;m.Tb.prototype.Dg=function(){return 1};var Xb=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,Zb=/[()']|%5B|%5D|%25/g,$b={"'":"%27","(":"%28",")":"%29","%5B":"[","%5D":"]","%25":"%"},Ub={};ac.prototype.Se=!0;ac.prototype.Ie=function(){return""};ac.prototype.rk=!0;ac.prototype.Dg=function(){return 1};var bc={};var ic,lc,Ni,dc;m.cc.prototype.rk=!0;m.cc.prototype.Dg=function(){return this.k};m.cc.prototype.Se=!0;m.cc.prototype.Ie=function(){return this.j};ic=/^[a-zA-Z0-9-]+$/;lc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};Ni={EMBED:!0,IFRAME:!0,LINK:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,TEMPLATE:!0};dc={};m.Oi=m.gc("",0);var qc={};var tc=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uc=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.g=m.wc.prototype;m.g.clone=function(){return new m.wc(this.x,this.y)};m.g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};m.g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.x*=a;this.y*=c;return this};a:{var Pi=m.ea.navigator;if(Pi){var Qi=Pi.userAgent;if(Qi){m.yc=Qi;break a}}m.yc=""};var Si,Kc,Jc,Wi,Xi;m.Sf=zc();m.D=Ac();m.Fc=m.xc("Gecko")&&!(m.Ga(m.yc.toLowerCase(),"webkit")&&!Cc())&&!(m.xc("Trident")||m.xc("MSIE"))&&!Cc();m.Gc=m.Ga(m.yc.toLowerCase(),"webkit")&&!Cc();m.Gc&&m.xc("Mobile");m.Qf=m.xc("Macintosh");m.Pf=m.xc("Windows");m.Ri=m.xc("Linux")||m.xc("CrOS");Si=m.ea.navigator||null;Si&&m.Ga(Si.appVersion||"","X11");m.Ti=m.xc("Android");m.Ui=m.Dc();m.Vi=m.xc("iPad");
Kc=function(){if(m.Sf&&m.ea.opera){var a=m.ea.opera.version;return m.na(a)?a():a}var a="",b=Ec();b&&(a=b?b[1]:"");return m.D&&!Cc()&&(b=Hc(),b>(0,window.parseFloat)(a))?String(b):a}();Jc={};Wi=m.ea.document;Xi=Hc();m.Mc=!Wi||!m.D||!Xi&&Cc()?void 0:Xi||("CSS1Compat"==Wi.compatMode?(0,window.parseInt)(Kc,10):5);var Wc;Wc=!m.D||m.Lc(9);m.Yi=!m.Fc&&!m.D||m.D&&m.Lc(9)||m.Fc&&m.Ic("1.9.1");m.Zi=m.D&&!m.Ic("9");m.$i=m.D||m.Sf||m.Gc;m.aj=m.D&&!m.Lc(9);var Qc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.bj=m.gd(!1);m.cj=m.gd(!0);m.dj=m.gd(null);m.kd="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.id.prototype.next=function(){throw m.kd;};m.id.prototype.Fb=function(){return this};var rd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,pd=m.Gc;var Cd={},Bd=0,ej=m.n("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",ej,void 0);m.Dd.prototype.yb=function(){return{version:this.version,args:this.args}};m.Ed.prototype.toString=function(){return this.j};var fj=m.n("yt.pubsub2.instance_")||new m.$a;m.$a.prototype.subscribe=m.$a.prototype.subscribe;m.$a.prototype.unsubscribeByKey=m.$a.prototype.yc;m.$a.prototype.publish=m.$a.prototype.W;m.$a.prototype.clear=m.$a.prototype.clear;m.l("yt.pubsub2.instance_",fj,void 0);m.gj=m.n("yt.pubsub2.subscribedKeys_")||{};m.l("yt.pubsub2.subscribedKeys_",m.gj,void 0);m.hj=m.n("yt.pubsub2.topicToKeys_")||{};m.l("yt.pubsub2.topicToKeys_",m.hj,void 0);m.ij=m.n("yt.pubsub2.isAsync_")||{};
m.l("yt.pubsub2.isAsync_",m.ij,void 0);m.l("yt.pubsub2.skipSubKey_",null,void 0);m.t(Hd,m.Dd);var $d=new m.Ed("timing-sent",Hd);var Vd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Qd=(0,m.q)(Vd.clearResourceTimings||Vd.webkitClearResourceTimings||Vd.mozClearResourceTimings||Vd.msClearResourceTimings||Vd.oClearResourceTimings||m.fa,Vd),Kd=Vd.mark?function(a){Vd.mark(a)}:m.fa;m.fe=m.qd;var le={enablejsapi:1},me={},ne={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ke.prototype.clone=function(){var a=new ke,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.Ib(c):a[b]=c}return a};m.qe=null;m.jj=m.Gc?"webkit":m.Fc?"moz":m.D?"ms":m.Sf?"o":"";m.kj=m.n("yt.dom.getNextId_");if(!m.kj){m.kj=function(){return++lj};m.l("yt.dom.getNextId_",m.kj,void 0);var lj=0};m.g=m.te.prototype;m.g.Va=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.touches=null;m.g.changedTouches=null;m.g.preventDefault=function(){this.Va.returnValue=!1;this.Va.preventDefault&&this.Va.preventDefault()};
m.g.stopPropagation=function(){this.Va.cancelBubble=!0;this.Va.stopPropagation&&this.Va.stopPropagation()};m.g.stopImmediatePropagation=function(){this.Va.cancelBubble=!0;this.Va.stopImmediatePropagation&&this.Va.stopImmediatePropagation()};var ue={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.we=m.n("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.we,void 0);var xe=m.n("yt.events.counter_")||{count:0};m.l("yt.events.counter_",xe,void 0);m.Be=/\s*;\s*/;m.g=m.ze.prototype;m.g.isEnabled=function(){return window.navigator.cookieEnabled};m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.da(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.G)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.Be),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.da(this.get(a));this.set(a,"",0,b,c);return d};m.g.sb=m.aa(4);m.g.Xa=m.aa(5);m.g.isEmpty=function(){return!this.j.cookie};m.g.Wa=m.aa(2);m.g.xf=m.aa(6);m.g.clear=function(){for(var a=m.Ae(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.De=new m.ze(window.document);m.De.k=3950;Ne.prototype.get=function(){var a;0<this.k?(this.k--,a=this.j,this.j=a.next,a.next=null):a=this.l();return a};Ne.prototype.put=function(a){this.n(a);this.k<this.A&&(this.k++,a.next=this.j,this.j=a)};var Ye;var Ze=new Ne(function(){return new Re},function(a){a.reset()},100);Qe.prototype.add=function(a,b){var c=Ze.get();c.set(a,b);this.k?this.k.next=c:this.j=c;this.k=c};Qe.prototype.remove=function(){var a=null;this.j&&(a=this.j,this.j=this.j.next,this.j||(this.k=null),a.next=null);return a};Re.prototype.set=function(a,b){this.Id=a;this.scope=b;this.next=null};Re.prototype.reset=function(){this.next=this.scope=this.Id=null};var Te,Ve=!1,We=new Qe;ef.prototype.reset=function(){this.context=this.k=this.l=this.j=null;this.n=!1};var gf=new Ne(function(){return new ef},function(a){a.reset()},100);m.bf.prototype.then=function(a,b,c){return m.qf(this,m.na(a)?a:null,m.na(b)?b:null,c)};m.$e(m.bf);m.bf.prototype.cancel=function(a){0==this.j&&Se(function(){var b=new rf(a);kf(this,b)},this)};m.bf.prototype.J=function(a){this.j=0;df(this,2,a)};m.bf.prototype.F=function(a){this.j=0;df(this,3,a)};
m.bf.prototype.P=function(){for(var a=null;a=nf(this);)of(this,a,this.j,this.C);this.B=!1};var uf=Oe;m.t(rf,m.wa);rf.prototype.name="cancel";var yf={};Af.prototype.l=function(a){zf(this.j,"startFeedback",arguments)};Af.prototype.n=function(a){zf(this.j,"startHelp",arguments)};Af.prototype.k=function(a){zf(this.j,"loadChatSupport",arguments)};var mj=!1,nj="";
if(window.navigator.plugins&&window.navigator.plugins.length){var oj=window.navigator.plugins["Shockwave Flash"];oj&&(mj=!0,oj.description&&(nj=Cf(oj.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(mj=!0,nj="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var pj=window.navigator.mimeTypes["application/x-shockwave-flash"];(mj=pj&&pj.enabledPlugin)&&(nj=Cf(pj.enabledPlugin.description))}else try{var qj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),mj=
!0,nj=Cf(qj.GetVariable("$version"))}catch(aaa){try{qj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),mj=!0,nj="6.0.21"}catch(baa){try{qj=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),mj=!0,nj=Cf(qj.GetVariable("$version"))}catch(caa){}}}m.rj=mj;m.sj=nj;var vj;m.Hf=m.xc("Firefox");m.tj=m.Dc()||m.xc("iPod");m.uj=m.xc("iPad");vj=m.xc("Android")&&!(Bc()||m.xc("Firefox")||zc()||m.xc("Silk"));m.Jf=Bc();m.If=m.xc("Safari")&&!(Bc()||m.xc("Coast")||zc()||Ac()||m.xc("Silk")||m.xc("Android"))&&!(m.Dc()||m.xc("iPad")||m.xc("iPod"));var Ff=function(){if(m.Hf)return Df(/Firefox\/([0-9.]+)/);if(m.D||m.Sf)return Kc;if(m.Jf)return Df(/Chrome\/([0-9.]+)/);if(m.If&&!(m.Dc()||m.xc("iPad")||m.xc("iPod")))return Df(/Version\/([0-9.]+)/);if(m.tj||m.uj){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.yc))return a[1]+"."+a[2]}else if(vj)return(a=Df(/Android\s+([0-9.]+)/))?a:Df(/Version\/([0-9.]+)/);return""}();m.l("userfeedback.api.isBrowserSupportedForGenie",function(){return Gf()},void 0);m.l("userfeedback.api.isBrowserSupportedForHelp",Gf,void 0);m.ga(Kf);Kf.prototype.getVersion=function(){return[this.j,this.k,this.l]};m.g=m.Uf.prototype;m.g.getHeight=function(){return this.bottom-this.top};m.g.clone=function(){return new m.Uf(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.Vf(this,a)};m.g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Xf={};m.wj=m.hd(function(){if(m.D)return m.Ic("10.0");var a=window.document.createElement("DIV"),b=m.Tf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b={style:c};if(!ic.test("div"))throw Error("Invalid tag name <div>.");if("DIV"in Ni)throw Error("Tag name <div> is not allowed for SafeHtml.");b=m.hc("div",b);m.nc(a,b);a=a.firstChild;b=a.style[m.Na("transition")];return""!=("undefined"!==typeof b?b:a.style[m.Wf(a,"transition")]||"")});var gg;m.cg={};gg=!1;var Bg,yj;m.xj=!m.D||m.Lc(9);Bg=!m.D||m.Lc(9);yj=m.D&&!m.Ic("9");!m.Gc||m.Ic("528");m.Fc&&m.Ic("1.9b")||m.D&&m.Ic("8")||m.Sf&&m.Ic("9.5")||m.Gc&&m.Ic("528");m.Fc&&!m.Ic("8")||m.D&&m.Ic("9");m.ig.prototype.stopPropagation=function(){this.af=!0};m.ig.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Wp=!1};m.zj=m.D?"focusin":"DOMFocusIn";m.Aj=m.Gc?"webkitTransitionEnd":m.Sf?"otransitionend":"transitionend";m.t(m.jg,m.ig);
m.jg.prototype.init=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;d?m.Fc&&(m.va(d,"nodeName")||(d=null)):"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=m.Gc||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=m.Gc||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.Va=a;a.defaultPrevented&&this.preventDefault()};m.jg.prototype.stopPropagation=function(){m.jg.D.stopPropagation.call(this);this.Va.stopPropagation?this.Va.stopPropagation():this.Va.cancelBubble=!0};
m.jg.prototype.preventDefault=function(){m.jg.D.preventDefault.call(this);var a=this.Va;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,yj)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};m.jg.prototype.Xj=m.aa(7);var ng;m.lg="closure_listenable_"+(1E6*Math.random()|0);ng=0;m.pg.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.j[f];a||(a=this.j[f]=[],this.k++);var h=m.rg(a,b,d,e);-1<h?(b=a[h],c||(b.Bh=!1)):(b=new mg(b,this.src,f,!!d,e),b.Bh=c,a.push(b));return b};m.pg.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.j))return!1;var e=this.j[a];b=m.rg(e,b,c,d);return-1<b?(og(e[b]),m.Ua(e,b),0==e.length&&(delete this.j[a],this.k--),!0):!1};
m.pg.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.j)if(!a||c==a){for(var d=this.j[c],e=0;e<d.length;e++)++b,og(d[e]);delete this.j[c];this.k--}return b};var wg="closure_lm_"+(1E6*Math.random()|0),Dg={},zg=0,Gg="__closure_events_fn_"+(1E9*Math.random()>>>0);m.ga(m.Hg);m.Ig=m.n("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.Ig,void 0);m.g=m.Hg.prototype;m.g.get=function(a,b){Kg(a);Jg(a);var c=void 0!==m.Ig[a]?m.Ig[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Kg(a);Jg(a);if(null==b)throw"ExpectedNotNull";m.Ig[a]=b.toString()};m.g.remove=function(a){Kg(a);Jg(a);delete m.Ig[a]};m.g.save=function(){var a;a=[];for(var b in m.Ig)a.push(b+"="+(0,window.escape)(m.Ig[b]));a=a.join("&");m.Ce("PREF",a,63072E3)};
m.g.clear=function(){m.Ig={}};var Ug=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Wg;var Bj=m.yc,Bj=Bj.toLowerCase();if(m.Ga(Bj,"android")){var Cj=Bj.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Cj)Wg=Number(Cj[1]);else{var Dj={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Ej=Bj.match("("+m.Db(Dj).join("|")+")");Wg=Ej?Dj[Ej[0]]:0}}else Wg=void 0;m.t(m.Yg,Xg);m.Yg.prototype.Wa=m.aa(1);m.Yg.prototype.clear=function(){var a=m.md(this.Fb(!0)),b=this;(0,m.A)(a,function(a){b.remove(a)})};m.t(m.Zg,m.Yg);m.g=m.Zg.prototype;m.g.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.j.removeItem(a)};
m.g.Wa=m.aa(0);m.g.Fb=function(a){var b=0,c=this.j,d=new m.id;d.next=function(){if(b>=c.length)throw m.kd;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.j.clear()};m.g.key=function(a){return this.j.key(a)};m.t(m.$g,m.Zg);m.t(ah,m.Zg);m.dh.prototype.yb=function(a){var b=[];eh(this,a,b);return b.join("")};var hh={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},gh=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.ih.prototype.set=function(a,b){m.da(b)?this.j.set(a,m.ch(b)):this.j.remove(a)};m.ih.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.bh(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.ih.prototype.remove=function(a){this.j.remove(a)};m.t(jh,m.ih);jh.prototype.set=function(a,b){jh.D.set.call(this,a,lh(b))};jh.prototype.k=function(a){a=jh.D.get.call(this,a);if(!m.da(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};jh.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.da(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(m.mh,jh);m.mh.prototype.set=function(a,b,c){if(b=lh(b)){if(c){if(c<(0,m.G)()){m.mh.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.G)()}m.mh.D.set.call(this,a,b)};m.mh.prototype.k=function(a,b){var c=m.mh.D.k.call(this,a);if(c)if(!b&&m.nh(c))m.mh.prototype.remove.call(this,a);else return c};m.t(m.oh,m.mh);var Fj,Gj;Fj=new m.$g;m.qh=Fj.isAvailable()?new m.oh(Fj):null;Gj=new ah;m.rh=Gj.isAvailable()?new m.oh(Gj):null;m.t(uh,m.u);m.g=uh.prototype;m.g.getId=function(){return this.S};m.g.Sl=function(a,b){this.Na()||(wh(this,a),Ch(this,b),this.P&&yh(this))};m.g.Xs=function(){return this.Eb};
m.g.eB=function(){if(!this.Ea){var a=Dh(this);if(a&&"html5"==Gh(this))this.J="html5",this.P||this.Wf();else if(Hh(this),this.J="html5",a&&this.vb)this.B.appendChild(this.vb),this.Wf();else{this.j.loaded=!0;var b=(0,m.q)(function(){var a=this.B,b=this.j.clone();m.n("yt.player.Application.create")(a,b);this.Wf()},this);this.C=b;this.Ea=!0;a?this.C():(this.j.assets.js2?(this.C=a=(0,m.q)(function(){m.rc(this.j.assets.js2,b);this.C=b},this),m.rc(this.j.assets.js,a)):m.rc(this.j.assets.js,this.C),m.Tg(this.j.assets.css))}}};
m.g.dB=function(){var a=this.j.clone();if(!this.F){var b=Bh(this);b&&(this.F=window.document.createElement("span"),this.F.tabIndex=0,this.lb.push(m.K(this.F,"focus",(0,m.q)(this.cp,this))),this.R=window.document.createElement("span"),this.R.tabIndex=0,this.lb.push(m.K(this.R,"focus",(0,m.q)(this.cp,this))),m.$c(this.F,b),m.ad(this.R,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Gh(this)?(this.J="flash",this.P||Rg(a,!1,(0,m.q)(this.Wf,this))):(Hh(this),this.J=
"flash",this.j.loaded=!0,m.Og(this.B,a),this.Wf())};m.g.cp=function(){Bh(this).focus()};
m.g.Wf=function(){var a=Bh(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.Ea=!1,a.isNotServable&&a.isNotServable(this.j.args.video_id))Ah(this);else{vh(this);this.P=!0;a=Bh(this);a.addEventListener&&(this.O=Eh(this,a,"addEventListener"));a.removeEventListener&&(this.Za=Eh(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.k[e]||(this.k[e]=Eh(this,a,e))}for(var f in this.A)this.O(f,
this.A[f]);yh(this);this.bb&&this.bb(this.k);this.$.W("onReady",this.k);a.apiProxyReady&&a.apiProxyReady()}else this.kc=m.x((0,m.q)(this.Wf,this),50)};m.g.rB=function(){return this.P};m.g.rd=function(a,b){if(!this.Na()){var c=xh(this,b);if(c){if(!m.Ra(this.ud,a)&&!this.A[a]){var d=Fh(this,a);this.O&&this.O(a,d)}this.$.subscribe(a,c);"onReady"==a&&this.P&&m.x(m.r(c,this.k),0)}}};m.g.cA=function(a,b){if(!this.Na()){var c=xh(this,b);c&&this.$.hf(a,c)}};
m.g.xs=function(a){a=a?cd:bd;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.F||b==this.R||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.LA=function(a){m.B("a11y-announce",a)};m.g.yy=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?th().volume:m.vc(a.volume,0,100);b.muted=void 0==a.muted?th().muted:a.muted;m.ph("yt-player-volume",b,2592E3)};m.g.wy=function(a){5==a&&Ah(this)};m.g.zy=function(a){m.B("WATCH_LATER_VIDEO_ADDED",a)};
m.g.Ay=function(a){m.B("WATCH_LATER_VIDEO_REMOVED",a)};m.g.ly=function(a){if(!m.dd(this.B,m.ye(a)))this.k.onExternalMouseMove()};m.g.ky=function(){m.sg(window.document,"mousemove",this.ly,!1,this)};m.g.my=function(){this.Kc&&(this.ub||(this.Qa=m.Rc(window.document)),this.U||(this.U=m.sg(window,"scroll",this.Gz,!1,this)));this.ub=!0};m.g.ny=function(){this.U&&(m.Cg(this.U),this.U=null);this.ub=!1};m.g.hp=function(a){this.ub&&!this.Kc&&a.preventDefault()};
m.g.Gz=function(){this.Qa&&window.scrollTo(this.Qa.x,this.Qa.y)};
m.g.fB=function(){Hh(this);this.J="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');b=
this.j.messages.player_fallback||a;a=m.E("player-unavailable");m.E("unavailable-submessage")&&a&&(m.E("unavailable-submessage").innerHTML=b,(b=m.F("icon",a))&&m.pc(b,"icon")&&(b.src=m.C(b,"icon")),m.J(a,"hid"),m.I(m.E("player"),"off-screen-trigger"))};m.g.Zs=function(){return this.J||Gh(this)};m.g.Ys=function(){return this.Lb};m.g.cancel=function(){if(this.C){var a=this.C,b=m.sc(this.j.assets.js);window.spf.script.ignore(b,a)}m.fb(this.kc);this.Ea=!1};
m.g.L=function(){Hh(this);this.hb=null;for(var a in this.A)m.ea[this.A[a]]=null;this.k=null;delete this.B;delete this.n;this.j&&(this.Eb=this.j=this.j.fallback=null);uh.D.L.call(this)};var Kh={},Jh="player_uid_"+(1E9*Math.random()>>>0);var Hj=m.n("yt.abuse.botguardInitialized")||pe;m.l("yt.abuse.botguardInitialized",Hj,void 0);var Ij=m.n("yt.abuse.invokeBotguard")||m.re;m.l("yt.abuse.invokeBotguard",Ij,void 0);var Jj=m.n("yt.player.exports.navigate")||m.Me;m.l("yt.player.exports.navigate",Jj,void 0);var Kj=m.n("yt.player.embed")||m.Ih;m.l("yt.player.embed",Kj,void 0);var Lj=m.n("yt.player.destroy")||m.Nh;m.l("yt.player.destroy",Lj,void 0);var Mj=m.n("yt.player.cancelAll")||Mh;m.l("yt.player.cancelAll",Mj,void 0);
var Nj=m.n("yt.player.getPlayerByElement")||m.Oh;m.l("yt.player.getPlayerByElement",Nj,void 0);var Oj=m.n("yt.player.exports.feedbackStart")||m.eg;m.l("yt.player.exports.feedbackStart",Oj,void 0);var Pj=m.n("yt.player.exports.feedbackShowArticle")||m.hg;m.l("yt.player.exports.feedbackShowArticle",Pj,void 0);var Qj=m.n("yt.util.activity.init")||m.Fe;m.l("yt.util.activity.init",Qj,void 0);var Rj=m.n("yt.util.activity.getTimeSinceActive")||m.He;m.l("yt.util.activity.getTimeSinceActive",Rj,void 0);
var Sj=m.n("yt.util.activity.setTimestamp")||Ge;m.l("yt.util.activity.setTimestamp",Sj,void 0);var Sh,Xh;m.Wh=null;Xh="";var $h=[];var fi,Ai,zi,gi,ii,qi,ki,mi,ti;gi=0;ii=[900,60,"waiting"];qi=[500,99,"waiting"];ki=[300,60,"waiting"];mi=[400,99,"waiting"];ti=[300,101,"done"];window.yt=window.yt||{};m.l("yt.setConfig",m.ab,void 0);m.l("yt.getConfig",m.w,void 0);m.l("yt.hasMsg",m.ib,void 0);m.l("yt.pubsub.publish",m.B,void 0);m.l("yt.pubsub.subscribe",m.y,void 0);m.l("yt.setMsg",function(a){bb(m.jb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){bb(m.jb,arguments)},void 0);m.l("yt.timing.report",ae,void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.w("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Yd(c)},void 0);m.l("ytcsi.tick",m.Id,void 0);m.t(Bi,m.xb);
Bi.prototype.enable=function(){window.onload=bi;window.onunload=ci;window.onerror=di;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",ei),window.addEventListener("spfpartprocess",ji),window.addEventListener("spfpartdone",oi),window.addEventListener("spfprocess",pi),window.addEventListener("spfdone",ri),window.addEventListener("spferror",ui),window.addEventListener("spfreload",vi),window.addEventListener("spfjsbeforeunload",Ci)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",wi),this.subscribe("dispose",yi)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Bi.prototype.init=function(){Bi.D.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.w("PAGEFRAME_JS")?(b=m.w("PAGEFRAME_JS"),c=function(){window.ytPageFrameLoaded=!0;m.n("ytbin.www.pageframe.setup")()}):a&&(a=m.n("yt.www.masthead.loadSearchbox"))&&a();var a=m.w("JS_COMMON_MODULE"),d=m.w("JS_PAGE_MODULES");d||(d=[a]);a=m.w("JS_DELAY_LOAD",void 0);0<a?(m.fb(this.l),this.l=m.x(function(){b&&m.rc(b,c);window.spf.script.require(d)},a)):(b&&m.rc(b,
c),window.spf.script.require(d));Qh();var a=!!m.n("yt.reactLoaded"),e=m.w("REACT_JS");!a&&e&&m.rc(e,function(){m.l("yt.reactLoaded",!0,void 0)})};Bi.prototype.dispose=function(){m.fb(this.l);var a=m.n("ytbin.www.pageframe.cancelSetup");a&&a();m.gb(Sh);if(a=m.Uh())a.removeEventListener("onReady",Th),a.removeEventListener("onStateChange",Th);Bi.D.dispose.call(this)};
Bi.prototype.disable=function(){Bi.D.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",ei),window.removeEventListener("spfpartprocess",ji),window.removeEventListener("spfpartdone",oi),window.removeEventListener("spfprocess",pi),window.removeEventListener("spfdone",ri),window.removeEventListener("spferror",ui),window.removeEventListener("spfreload",vi),window.removeEventListener("spfjsbeforeunload",Ci));window.onload=null;window.onunload=null;window.onerror=null};
m.zb(new Bi);})(_yt_www);
